### ISSUE TITLE
Steward perk "Bannerlord" not being applied

### ISSUE THREAD

**Issue by Sons-of-Man** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#139]
Steward perk "Bannerlord" still not working for me for some reason. Is there any incompatibilities that should be mentioned or load order? I am using Bannerlord Tweaks mod, CITEditor and a few others that I am certain aren't causing any problems. Any help is appreciated, thanks!

**Comment by Skau** [comment]
It should be working. What version are you on?

**Comment by Sons-of-Man** [comment]
> It should be working. What version are you on?

Beta branch 1.1.0. Saw no huge need too update too the next. Could one of those tiny fixes/reversions possibly break this?

**Comment by Skau** [comment]
Look at my edit on last original comment.

**Comment by Sons-of-Man** [comment]
Ah alrighty, been clueless for the past couple hours fiddling around trying to find out what was causing it. Would have never guessed this too be the reason but had a small feeling Bannerlord Tweaks may have been overwriting so I moved Community Patch towards the end of the load order, since that didn't fix it, here I am lol.

**Comment by Tyler-IN** [comment]
Load order won't matter for this - the patches are applied after campaign data is loaded.

We'd somehow need BL tweaks or other mods to apply the patches after we do if they want to patch the same methods.

We'd need to expose some sort of events around when we patch and then make a PR for BL Tweaks to have it detect our mod being loaded and patch after our patches are applied.

We're patching just to make fixes, they're patching to change behavior, so our policy since the beginning is don't interfere with non-default behavior...
e.g. If some other mod patches a broken function instead of using it, it could also be trying to fix it or accounts for it being broken and we don't want to interfere with what the other mod expects and cause it to break (e.g. double fixing it, doubling some number or causing general wackiness).

This needs some more investigation and we'd like feedback from the authors of the affected mods - if they want to just copy our fixes into their mods that works fine and it's less work for us - otherwise we need to coordinate, or the other mods can be careful what they patch and test their compatibility with our patches.

**Comment by Skau** [comment]
@Sons-of-Man Could you try disabling PartySizeTweakEnabled in the Bannerlord Tweak settings and see if it works then?

**Comment by Sons-of-Man** [comment]
> @Sons-of-Man Could you try disabling PartySizeTweak in the Bannerlord Tweak settings and see if it works then?

Can confirm this has fixed it, but would it be better off disabling the whole mod since it will just overwrite constantly?

**Comment by Skau** [comment]
Great. 
No, it's fine, they don't patch at all when the whole module like that is disabled. If you had it enabled, but instead had either of the sub settings, `LeadershipPartySizeBonus` or `StewardPartySizeBonus` (or none of them for that matter), our patch wouldn't get through.

**Comment by Skau** [comment]
I'm not about to go through all their source code though and see what affects our fixes or not. So do it if you want. If you find any more issues, just let us know. Or just disable either Bannerlord Tweaks or Community Patch entirely.

**Comment by Tyler-IN** [comment]
Pinging @mipen from https://github.com/mipen/BannerlordTweaks
